
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

mqtt:
 sensor:
 - name: "Incubator Light Level"
   state_topic: "incubator/light/value"
   unit_of_measurement: "%"
   icon: mdi:sprout
 
 - name: "Incubator Moisture"
   state_topic: "incubator/moisture/value"
   unit_of_measurement: "%"
   icon: mdi:sprout

 number:
  - name: "Incubator Valve Threshold"
    command_topic: "incubator/moisture/threshold"
    icon: mdi:water-percent
    #device_class: "moisture"
    min: 0
    max: 100
    step: 1
    retain: True
  
  - name: "Incubator Light Threshold"
    command_topic: "incubator/light/threshold"
    icon: mdi:brightness-6
    #device_class: "illuminance"
    min: 0
    max: 100
    step: 1
    retain: True